[package]
name = "perform"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate_type = ["cdylib"]
name = "perform"  # so we get "librustLib.so"


