/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_MyTask */

#ifndef _Included_src_MyTask
#define _Included_src_MyTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_MyTask
 * Method:    performInRust
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_src_MyTask_performInRust
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
